### ISSUE TITLE
HomePage出问题

### ISSUE THREAD

**Issue by xzqm** [Tomotoes/HomePage#6]
按照readme配置，基本没动改了标题，推上去以后，电脑打开首页是全黑没有按键，手机上倒是能手动下滑正常打开

**Comment by xzqm** [comment]
不对，出来是出来了，但是等了好久才出了，但是转到到/blog画面有问题。。。

**Comment by xzqm** [comment]
主要还是首页显示出来太慢了，不多点几下根本出不来

**Comment by Tomotoes** [comment]
您好, 可能是之前依赖出了问题, 请使用最新版本.
