### ISSUE TITLE
script.pug中的anime.min.js文件的链接获取不到

### ISSUE THREAD

**Issue by a347807131** [Tomotoes/HomePage#8]
![image](https://user-images.githubusercontent.com/24996382/76003165-a17c9c80-5f42-11ea-8d17-f722bda8d587.png)
实际上，在clone下来dist文件夹下index.html里的引用为2.2.0版本，是能获取到的。

获取不到的结果就是，页面动画不能启动。

**Comment by Tomotoes** [comment]
您好, 最新版已修复了这个问题.

您如果不想升级最新版, 把链接替换成下面的即可:
`script(src="https://cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js")`

可能是之前, 我升级依赖的时候改完版本号没有测试.
